export default function Head() {
  return (
    <>
      <title>Tech-Gap</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta content="dark" name="color-scheme" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href='/public/favicon.png' />
    </>
  );
}
